# **Ejemplos de validación cruzada (Cross Validation)**

23_24

In [9]:
import numpy as np
from sklearn.model_selection import KFold, TimeSeriesSplit
import random

# En los siguientes ejemplos vamos a ver cómo estas librerías
# gestionan/generan los indices de los grupos que va a entrenar con la técnica
# de cross validation
# Importante: En este código no se aplica/busca un modelo. Sólo vemos cómo se realiza el Cross Validation

print('--------------------------------')
print('Para series NO temporales')
print('--------------------------------')

X = np.array(['a', 'b', 'c','d','e', 'f', 'g', 'h', 'i', 'j', 'k',
                'l', 'm', 'n', 'ñ', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
                 'w', 'x', 'y', 'z'])

kf = KFold(n_splits=5)
#para que genere el indice para el grupo de test de forma aleatoria...
#kf = KFold(n_splits=4,shuffle=True,random_state=random.randrange(4))
for train_index, test_index in kf.split(X):
    print('Indices para train: %s, indice para test %s'% (train_index,test_index))
    X_train, X_test = X[train_index], X[test_index]
    print('Valores de X_train:', X_train,' X_test: ', X_test)


--------------------------------
Para series NO temporales
--------------------------------
Indices para train: [ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26], indice para test [0 1 2 3 4 5]
Valores de X_train: ['g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'ñ' 'o' 'p' 'q' 'r' 's' 't' 'u' 'v' 'w'
 'x' 'y' 'z']  X_test:  ['a' 'b' 'c' 'd' 'e' 'f']
Indices para train: [ 0  1  2  3  4  5 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26], indice para test [ 6  7  8  9 10 11]
Valores de X_train: ['a' 'b' 'c' 'd' 'e' 'f' 'm' 'n' 'ñ' 'o' 'p' 'q' 'r' 's' 't' 'u' 'v' 'w'
 'x' 'y' 'z']  X_test:  ['g' 'h' 'i' 'j' 'k' 'l']
Indices para train: [ 0  1  2  3  4  5  6  7  8  9 10 11 17 18 19 20 21 22 23 24 25 26], indice para test [12 13 14 15 16]
Valores de X_train: ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'q' 'r' 's' 't' 'u' 'v'
 'w' 'x' 'y' 'z']  X_test:  ['m' 'n' 'ñ' 'o' 'p']
Indices para train: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 22 23 24 25 26], indice para test [17 18 19 

In [4]:
print('--------------------------------')
print('Para series temporales')
print('--------------------------------')

# Para series temporales, donde los valores elegidos en cada iteración
# no pueden ser aleatorios sino que han de estar ordenados
# Es decir, que el modelo no utilizará datos del futuro para
# predecir el pasado, sino que prediga el futuro con datos del pasado
X  = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
#y = np.array([1,2,3,4,5,6])
kfts=TimeSeriesSplit(n_splits=3)
# Lo que se obtiene en las variables train_index y test_index, son los indices
# de los grupos del array x que se van a entrenar
for train_index, test_index in kfts.split(X):
    print('%s %s'% (train_index,test_index))
    X_train, X_test = X[train_index], X[test_index]
    print('Valores de X_train:', X_train,' X_test: ', X_test)

    #y_train, y_test = y[train_index], y[test_index]
    #print('Valores de y_train:', y_train,' y_test: ', y_test)

--------------------------------
Para series temporales
--------------------------------
[0 1 2] [3]
Valores de X_train: [[1 2]
 [3 4]
 [5 6]]  X_test:  [[7 8]]
[0 1 2 3] [4]
Valores de X_train: [[1 2]
 [3 4]
 [5 6]
 [7 8]]  X_test:  [[ 9 10]]
[0 1 2 3 4] [5]
Valores de X_train: [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]  X_test:  [[11 12]]
